# Generated by Django 3.2.4 on 2021-06-29 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(verbose_name='session id')),
                ('category', models.CharField(max_length=50, verbose_name='category')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('data', models.JSONField(verbose_name='payload data')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='event datetime')),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
            },
        ),
    ]
