# Generated by Django 3.2.4 on 2021-06-29 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, null=True, verbose_name='payload error data')),
                ('message', models.CharField(blank=True, max_length=150, null=True, verbose_name='error message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'error',
                'verbose_name_plural': 'errors',
            },
        ),
    ]
